services:
  mysql:
    image: mysql:8.0
    container_name: myworkout-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myworkout
    ports:
      - "3307:3306"
    volumes:
      - myworkout_mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  myworkout_mysql_data:
