version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: myworkout-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myworkout
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  core-api:
    build:
      context: ./core-api-node
    container_name: myworkout-core-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: myworkout
      PORT: 3000
    ports:
      - "3000:3000" # ⬅️ DESCOMENTADO (acceso directo desde host)
    depends_on:
      mysql:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: myworkout-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  analytics-api:
    build:
      context: ./analytics-api-fastapi
    container_name: myworkout-analytics-api
    environment:
      CORE_API_BASE: http://core-api:3000
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: myworkout
    ports:
      - "8000:8000"
    depends_on:
      - core-api
      - mongo

  gateway:
    build:
      context: ./gateway
    container_name: myworkout-gateway
    environment:
      PORT: 8080
      CORE_API_TARGET: http://core-api:3000
      ANALYTICS_API_TARGET: http://analytics-api:8000
    ports:
      - "8080:8080"
    depends_on:
      - core-api
      - analytics-api

  frontend:
    build:
      context: ./frontend-angular/frontend-angular
    container_name: myworkout-frontend
    ports:
      - "4200:4200"
    depends_on:
      - gateway

volumes:
  mysql_data:
  mongo_data:
